// <auto-generated />
using System;
using ImprovShowPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImprovShowPlanner.Migrations
{
    [DbContext(typeof(ImprovShowContext))]
    [Migration("20181218175826_foreignKeyTest7")]
    partial class foreignKeyTest7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImprovShowPlanner.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc");

                    b.Property<int>("GameTypeId");

                    b.Property<string>("Name");

                    b.Property<int>("NumPlayers");

                    b.HasKey("GameId");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameForm");

                    b.HasKey("GameTypeId");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.IndivShow", b =>
                {
                    b.Property<int>("IndivShowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("IndivShowId");

                    b.ToTable("IndivShows");
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("NewPlayer");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId");

                    b.Property<int>("IndivShowId");

                    b.Property<int>("PlayerId");

                    b.HasKey("ShowId");

                    b.HasIndex("GameId");

                    b.HasIndex("IndivShowId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.Game", b =>
                {
                    b.HasOne("ImprovShowPlanner.Models.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ImprovShowPlanner.Models.Show", b =>
                {
                    b.HasOne("ImprovShowPlanner.Models.Game", "Game")
                        .WithMany("ShowDetails")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ImprovShowPlanner.Models.IndivShow", "IndivShow")
                        .WithMany("ShowDetails")
                        .HasForeignKey("IndivShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ImprovShowPlanner.Models.Player", "Player")
                        .WithMany("ShowDetails")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
